/*
 * BookAddInterFrm.java
 *
 * Created on __DATE__, __TIME__
 */

package hzu.com.cn.view;

import hzu.com.cn.dao.BookDao;
import hzu.com.cn.dao.BookTypeDao;
import hzu.com.cn.dao.BuyDao;
import hzu.com.cn.dao.SaleDao;
import hzu.com.cn.dao.StockDao;
import hzu.com.cn.model.Book;
import hzu.com.cn.model.BookType;
import hzu.com.cn.model.Buy;
import hzu.com.cn.model.Sale;
import hzu.com.cn.model.Stock;
import hzu.com.cn.util.DBUtil;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;

import javax.swing.JOptionPane;
import java.util.Date;
import java.text.SimpleDateFormat;
/**
 *
 * @author  __USER__
 */
public class BookAddInterFrm extends javax.swing.JInternalFrame {
	DBUtil dbUtil = new DBUtil();
	BookTypeDao bookTypeDao = new BookTypeDao();
	BookDao bookDao = new BookDao();
	StockDao stockDao=new StockDao();
	SaleDao saleDao=new SaleDao();
	BuyDao buyDao=new BuyDao();
	/** Creates new form BookAddInterFrm */
	public BookAddInterFrm() {
		initComponents();
		this.fillBookType();
		this.jCBookType.setSelectedIndex(0);
	}

	private void fillBookType() {
		Connection con = null;
		BookType bookType = null;
		try {
			con = dbUtil.getCon();
			ResultSet rs = bookTypeDao.bookTyeList(con, new BookType());
			while (rs.next()) {
				bookType = new BookType();
				bookType.setId(rs.getInt("id"));
				bookType.setBookTypeName(rs.getString("bookTypeName"));
				this.jCBookType.addItem(bookType);

			}
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	public String time(){
		SimpleDateFormat df=new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
		return df.format(new Date());
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

jLabel1 = new javax.swing.JLabel();
jBookNameAdd = new javax.swing.JTextField();
jLabel2 = new javax.swing.JLabel();
jBookAuthorAdd = new javax.swing.JTextField();
jLabel3 = new javax.swing.JLabel();
jLabel4 = new javax.swing.JLabel();
jBookPriceAdd = new javax.swing.JTextField();
jLabel5 = new javax.swing.JLabel();
jCBookType = new javax.swing.JComboBox();
jLabel6 = new javax.swing.JLabel();
jScrollPane1 = new javax.swing.JScrollPane();
jBookDescTxt = new javax.swing.JTextArea();
jBBookAdd = new javax.swing.JButton();
jBBookReset = new javax.swing.JButton();
jLabel7 = new javax.swing.JLabel();
jBookAmountAdd = new javax.swing.JTextField();
jLabel8 = new javax.swing.JLabel();
jBookPressAdd = new javax.swing.JTextField();

setClosable(true);
setIconifiable(true);
setTitle("\u56fe\u4e66\u6dfb\u52a0");

jLabel1.setText("\u56fe\u4e66\u540d\u79f0");

jLabel2.setText("\u56fe\u4e66\u4f5c\u8005");

jLabel3.setText("\u51fa\u7248\u793e");

jLabel4.setText("\u56fe\u4e66\u4ef7\u683c");

jLabel5.setText("\u56fe\u4e66\u7c7b\u522b");

jLabel6.setText("\u56fe\u4e66\u63cf\u8ff0");

jBookDescTxt.setColumns(20);
jBookDescTxt.setRows(5);
jScrollPane1.setViewportView(jBookDescTxt);

jBBookAdd.setText("\u6dfb\u52a0");
jBBookAdd.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
jBBookAddActionPerformed(evt);
}
});

jBBookReset.setText("\u91cd\u7f6e");
jBBookReset.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
jBBookResetActionPerformed(evt);
}
});

jLabel8.setText("\u6570\u91cf");

javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
getContentPane().setLayout(layout);
layout.setHorizontalGroup(
layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addGap(300, 300, 300)
.addComponent(jLabel2)
.addGap(48, 48, 48)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addComponent(jBookPressAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
.addGap(291, 291, 291)
.addComponent(jLabel7))
.addComponent(jBookAuthorAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
.addGroup(layout.createSequentialGroup()
.addGap(49, 49, 49)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addComponent(jLabel1)
.addGap(18, 18, 18)
.addComponent(jBookNameAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
.addGroup(layout.createSequentialGroup()
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
.addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
.addComponent(jLabel5)
.addGap(18, 18, 18)
.addComponent(jCBookType, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
.addComponent(jLabel8))
.addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
.addComponent(jLabel4)
.addGap(18, 18, 18)
.addComponent(jBookPriceAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
.addGap(34, 34, 34)
.addComponent(jLabel3)))
.addGap(52, 52, 52)
.addComponent(jBookAmountAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
.addGroup(layout.createSequentialGroup()
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addComponent(jLabel6)
.addGap(18, 18, 18)
.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE))))
.addGroup(layout.createSequentialGroup()
.addGap(194, 194, 194)
.addComponent(jBBookAdd)
.addGap(170, 170, 170)
.addComponent(jBBookReset)))
.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
);
layout.setVerticalGroup(
layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addGap(34, 34, 34)
.addComponent(jLabel1)
.addGap(3, 3, 3)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addGap(42, 42, 42)
.addComponent(jLabel7))
.addGroup(layout.createSequentialGroup()
.addGap(34, 34, 34)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(jLabel4)
.addComponent(jBookPriceAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(jLabel3)
.addComponent(jBookPressAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
.addGroup(layout.createSequentialGroup()
.addGap(24, 24, 24)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(jBookNameAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(jLabel2)
.addComponent(jBookAuthorAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
.addGap(56, 56, 56)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(jLabel5)
.addComponent(jCBookType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(jLabel8)
.addComponent(jBookAmountAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
.addGap(46, 46, 46)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
.addGap(28, 28, 28)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(jBBookReset)
.addComponent(jBBookAdd)))
.addComponent(jLabel6))
.addGap(74, 74, 74))
);

pack();
}// </editor-fold>

	//GEN-END:initComponents
	private void jBBookAddActionPerformed(java.awt.event.ActionEvent evt) {
		String bookName = this.jBookNameAdd.getText();
		String author = this.jBookAuthorAdd.getText();
		String price = this.jBookPriceAdd.getText();
		String press=this.jBookPressAdd.getText();
		String amount=this.jBookAmountAdd.getText();
		String time=this.time();
		if ("".equals(bookName) || bookName == null) {
			JOptionPane.showMessageDialog(null, "图书名称不能为空");
			return;
		}
		if ("".equals(author) || author == null) {
			JOptionPane.showMessageDialog(null, "图书作者不能为空");
			return;
		}
		if ("".equals(price) || price == null) {
			JOptionPane.showMessageDialog(null, "图书价格不能为空");
			return;
		}
		if ("".equals(press) || press == null) {
			JOptionPane.showMessageDialog(null, "图书出版社不能为空");
			return;
		}
		if ("".equals(amount) || amount == null) {
			JOptionPane.showMessageDialog(null, "图书数量不能为空");
			return;
		}
		
		float price1 = Float.parseFloat(this.jBookPriceAdd.getText());
		
		String bookDesc = this.jBookDescTxt.getText();
		BookType BookType = (BookType) this.jCBookType.getSelectedItem();
		int bookTypeId = BookType.getId();
	
		Stock stock=new Stock(bookName,  author,  price1,  press,
				Integer.parseInt(amount),  bookDesc,  bookTypeId);
		
		Connection con = null;

		try {
			con = dbUtil.getCon();
			int addNum = stockDao.stockAdd(con, stock);
			if (addNum == 1) {
				JOptionPane.showMessageDialog(null, "图书添加成功！");
				
//////////////////////////////////	
				Buy buy=new Buy(bookName,  author,  price1,  press,Integer.parseInt(amount), time);
				con = null;
				try {
					con = dbUtil.getCon();
					int add = buyDao.buyAdd(con, buy);

					if (add == 1) {
						JOptionPane.showMessageDialog(null, "进购记录已经更新！");
						this.resetValue();
					} else {
						JOptionPane.showMessageDialog(null, "进购记录更新失败！");
					}
				} catch (Exception e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
					JOptionPane.showMessageDialog(null, "进购记录更新失败！");
				} finally {
					try {
						dbUtil.colseCon(con);
					} catch (SQLException e) {
						// TODO Auto-generated catch block
						e.printStackTrace();
					}
				}	
//////////////////////////////////				
				this.resetValue();
			} else {
				JOptionPane.showMessageDialog(null, "图书添加失败！");
			}
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
			JOptionPane.showMessageDialog(null, "图书添加失败！");
		} finally {
			try {
				dbUtil.colseCon(con);
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
		
	}

	private void jBBookResetActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		this.resetValue();
	}

	private void resetValue() {
		this.jBookNameAdd.setText("");
		this.jBookAuthorAdd.setText("");
		this.jBookPriceAdd.setText("");
		this.jCBookType.setSelectedIndex(0);
		this.jBookDescTxt.setText("");
		this.jBookAmountAdd.setText("");
		this.jBookPressAdd.setText("");
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jBBookAdd;
	private javax.swing.JButton jBBookReset;
	private javax.swing.JTextField jBookAmountAdd;
	private javax.swing.JTextField jBookAuthorAdd;
	private javax.swing.JTextArea jBookDescTxt;
	private javax.swing.JTextField jBookNameAdd;
	private javax.swing.JTextField jBookPressAdd;
	private javax.swing.JTextField jBookPriceAdd;
	private javax.swing.JComboBox jCBookType;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JScrollPane jScrollPane1;
	// End of variables declaration//GEN-END:variables

}