/*
 * BookTypeInterFrm.java
 *
 * Created on __DATE__, __TIME__
 */

package hzu.com.cn.view;

import java.sql.Connection;

import hzu.com.cn.dao.BookTypeDao;
import hzu.com.cn.model.BookType;
import hzu.com.cn.util.DBUtil;

import javax.swing.JOptionPane;

/**
 *
 * @author  __USER__
 */
public class BookTypeInterFrm extends javax.swing.JInternalFrame {
	DBUtil dbUtil=new DBUtil();
	BookTypeDao bookTypeDao=new  BookTypeDao();
	/** Creates new form BookTypeInterFrm */
	public BookTypeInterFrm() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jTBookType = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTBookDesc = new javax.swing.JTextArea();
		jBAdd = new javax.swing.JButton();
		jBReset = new javax.swing.JButton();

		setClosable(true);
		setIconifiable(true);
		setTitle("\u56fe\u4e66\u7c7b\u522b\u6dfb\u52a0");

		jLabel1.setText("\u56fe\u4e66\u7c7b\u522b");

		jLabel2.setText("\u7c7b\u522b\u63cf\u8ff0");

		jTBookDesc.setColumns(20);
		jTBookDesc.setRows(5);
		jScrollPane1.setViewportView(jTBookDesc);

		jBAdd.setIcon(new javax.swing.ImageIcon(
				"F:\\java 实训\\第三课\\images2\\add.png")); // NOI18N
		jBAdd.setText("\u6dfb\u52a0");
		jBAdd.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jBAddActionPerformed(evt);
			}
		});

		jBReset.setIcon(new javax.swing.ImageIcon(
				"F:\\java 实训\\第三课\\images2\\reset.png")); // NOI18N
		jBReset.setText("\u91cd\u7f6e");
		jBReset.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jBResetActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								layout.createSequentialGroup().addContainerGap(
										122, Short.MAX_VALUE).addComponent(
										jBAdd).addGap(64, 64, 64).addComponent(
										jBReset).addGap(127, 127, 127))
						.addGroup(
								layout
										.createSequentialGroup()
										.addGap(91, 91, 91)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(jLabel1)
														.addComponent(jLabel2))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(
																jTBookType)
														.addComponent(
																jScrollPane1,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																196,
																Short.MAX_VALUE))
										.addGap(80, 80, 80)));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGap(43, 43, 43)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(jLabel1)
														.addComponent(
																jTBookType,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																20,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(28, 28, 28)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel2)
														.addComponent(
																jScrollPane1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																120,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jBAdd)
														.addComponent(jBReset))
										.addGap(34, 34, 34)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jBAddActionPerformed(java.awt.event.ActionEvent evt) {
		String bookTypeName=this.jTBookType.getText();
		String bookTypeDesc=this.jTBookDesc.getText();
		if("".equals(bookTypeName)||bookTypeName==null){
			JOptionPane.showMessageDialog(null, "圖書類別不能為空");
			return;
		}
		BookType bookType=new BookType(bookTypeName,bookTypeDesc);
		Connection con=null;
		try {
			con=dbUtil.getCon();
			int n=bookTypeDao.bookTypeAdd(con, bookType);
			if(n==1){
				JOptionPane.showMessageDialog(null, "圖書類別添加成功！");
				this.jTBookType.setText("");
				this.jTBookDesc.setText("");
			}else{
				JOptionPane.showMessageDialog(null, "圖書類別添加失敗！");
			}
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
			JOptionPane.showMessageDialog(null, "圖書類別添加失敗！");
		}
	}

	private void jBResetActionPerformed(java.awt.event.ActionEvent evt) {
		this.jTBookType.setText("");
		this.jTBookDesc.setText("");
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jBAdd;
	private javax.swing.JButton jBReset;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextArea jTBookDesc;
	private javax.swing.JTextField jTBookType;
	// End of variables declaration//GEN-END:variables

}