/*
 * BookTypeManageInterFrm.java
 *
 * Created on __DATE__, __TIME__
 */

package hzu.com.cn.view;

import java.sql.Connection;
import java.sql.ResultSet;
import java.util.Vector;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import hzu.com.cn.dao.BookTypeDao;
import hzu.com.cn.model.BookType;
import hzu.com.cn.util.DBUtil;

/**
 *
 * @author  __USER__
 */
public class BookTypeManageInterFrm extends javax.swing.JInternalFrame {
	DBUtil dbUtil = new DBUtil();
	BookTypeDao bookTypeDao = new BookTypeDao();

	/** Creates new form BookTypeManageInterFrm */
	public BookTypeManageInterFrm() {
		initComponents();
		this.fillTable(new BookType());
	}

	private void fillTable(BookType bookType) {
		DefaultTableModel dtm = (DefaultTableModel) jBookTypeTable.getModel();
		dtm.setRowCount(0);
		Connection con = null;
		try {
			con = dbUtil.getCon();
			ResultSet rs = bookTypeDao.bookTyeList(con, bookType);
			while (rs.next()) {
				Vector v = new Vector();
				v.add(rs.getString("id"));
				v.add(rs.getString("bookTypeName"));
				v.add(rs.getString("bookTypeDesc"));
				dtm.addRow(v);
			}
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} finally {

			try {
				dbUtil.getCon();
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}

		}
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jBookTypeName = new javax.swing.JTextField();
		jBReaserch = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		jBookTypeTable = new javax.swing.JTable();
		jPanel1 = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		jBookTypeId = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		jBookTypeTxt = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		jScrollPane2 = new javax.swing.JScrollPane();
		jBookTypeDescTxt = new javax.swing.JTextArea();
		jBDelete = new javax.swing.JButton();
		jBModify = new javax.swing.JButton();

		setClosable(true);
		setIconifiable(true);
		setTitle("\u56fe\u4e66\u7c7b\u522b\u7ef4\u62a4");

		jLabel1.setText("\u56fe\u4e66\u7c7b\u522b\u540d\u79f0");

		jBReaserch.setText("\u67e5\u8be2");
		jBReaserch.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jBReaserchActionPerformed(evt);
			}
		});

		jBookTypeTable.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] {

				}, new String[] { "编号", "图书类别名称", "图书类别描述" }) {
			boolean[] canEdit = new boolean[] { false, false, false };

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		});
		jBookTypeTable.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				jBookTypeTableMousePressed(evt);
			}
		});
		jScrollPane1.setViewportView(jBookTypeTable);

		jPanel1.setBorder(javax.swing.BorderFactory
				.createTitledBorder("\u8868\u5355\u64cd\u4f5c"));

		jLabel2.setText("\u7f16\u53f7\uff1a");

		jLabel3.setText("\u56fe\u4e66\u7c7b\u522b\u540d\u79f0\uff1a");

		jLabel4.setText("\u63cf\u8ff0\uff1a");

		jBookTypeDescTxt.setColumns(20);
		jBookTypeDescTxt.setRows(5);
		jScrollPane2.setViewportView(jBookTypeDescTxt);

		jBDelete.setText("\u5220\u9664");
		jBDelete.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jBDeleteActionPerformed(evt);
			}
		});

		jBModify.setText("\u4fee\u6539");
		jBModify.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jBModifyActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGap(44, 44, 44)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(jLabel4)
														.addComponent(jLabel2))
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGap(
																				18,
																				18,
																				18)
																		.addComponent(
																				jBookTypeId,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				82,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(
																				26,
																				26,
																				26)
																		.addComponent(
																				jLabel3)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jBookTypeTxt,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				99,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGap(
																				38,
																				38,
																				38)
																		.addComponent(
																				jScrollPane2,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				201,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addContainerGap(34, Short.MAX_VALUE))
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel1Layout
										.createSequentialGroup()
										.addGap(89, 89, 89)
										.addComponent(jBDelete)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												133, Short.MAX_VALUE)
										.addComponent(jBModify).addGap(92, 92,
												92)));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel2)
														.addComponent(jLabel3)
														.addComponent(
																jBookTypeId,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jBookTypeTxt,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(34, 34, 34)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel4)
														.addComponent(
																jScrollPane2,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																86,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jBModify)
														.addComponent(jBDelete))
										.addContainerGap()));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGap(54, 54, 54)
										.addComponent(jLabel1)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jBookTypeName,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												126,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												53, Short.MAX_VALUE)
										.addComponent(jBReaserch).addGap(97,
												97, 97))
						.addGroup(
								layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																jScrollPane1,
																javax.swing.GroupLayout.Alignment.LEADING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																440,
																Short.MAX_VALUE)
														.addComponent(
																jPanel1,
																javax.swing.GroupLayout.Alignment.LEADING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE))
										.addContainerGap()));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGap(44, 44, 44)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel1)
														.addComponent(
																jBReaserch)
														.addComponent(
																jBookTypeName,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addComponent(
												jScrollPane1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												203,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												27, Short.MAX_VALUE)
										.addComponent(
												jPanel1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap()));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jBModifyActionPerformed(java.awt.event.ActionEvent evt) {
		String id = this.jBookTypeId.getText();
		String bookTypeName=this.jBookTypeTxt.getText();
		String bookTypeDesc=this.jBookTypeDescTxt.getText();
		if ("".equals(id) || id == null) {
			JOptionPane.showMessageDialog(null, "请选择要修改的记录");
			return;
		}
		BookType bookType=new BookType(Integer.parseInt(id),bookTypeName,bookTypeDesc);
		Connection con = null;
		
		try {
			con = dbUtil.getCon();
			int modifyNum = bookTypeDao.bookTypeModify(con, bookType);
			if (modifyNum == 1) {

				JOptionPane.showMessageDialog(null, "修改成功！");
				this.resetValue();
				this.fillTable(new BookType());

			} else {

				JOptionPane.showMessageDialog(null, "修改失败！");
			}

		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
			JOptionPane.showMessageDialog(null, "修改失败！");
		}
	}

	private void jBDeleteActionPerformed(java.awt.event.ActionEvent evt) {
		String id = this.jBookTypeId.getText();
		if ("".equals(id) || id == null) {
			JOptionPane.showMessageDialog(null, "请选择要删除的记录");
			return;
		}
		int n = JOptionPane.showConfirmDialog(null, "确定要删除这条记录吗？");
		if (n == 0) {
			Connection con = null;
			try {
				con = dbUtil.getCon();
				int deleteNum = bookTypeDao.bookTypeDelete(con, id);
				if (deleteNum == 1) {

					JOptionPane.showMessageDialog(null, "删除成功！");
					this.resetValue();
					this.fillTable(new BookType());

				} else {

					JOptionPane.showMessageDialog(null, "删除失败！");
				}

			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
				JOptionPane.showMessageDialog(null, "删除失败！");
			}

		}
	}

	private void resetValue() {
		this.jBookTypeId.setText("");
		this.jBookTypeTxt.setText("");
		this.jBookTypeDescTxt.setText("");

	}

	private void jBookTypeTableMousePressed(java.awt.event.MouseEvent evt) {
		int row = jBookTypeTable.getSelectedRow();
		this.jBookTypeId.setText((String) jBookTypeTable.getValueAt(row, 0));
		this.jBookTypeTxt.setText((String) jBookTypeTable.getValueAt(row, 1));
		this.jBookTypeDescTxt.setText((String) jBookTypeTable
				.getValueAt(row, 2));
	}

	private void jBReaserchActionPerformed(java.awt.event.ActionEvent evt) {
		String bookTypeName = this.jBookTypeName.getText();
		BookType bookType = new BookType();
		bookType.setBookTypeName(bookTypeName);
		this.fillTable(bookType);
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jBDelete;
	private javax.swing.JButton jBModify;
	private javax.swing.JButton jBReaserch;
	private javax.swing.JTextArea jBookTypeDescTxt;
	private javax.swing.JTextField jBookTypeId;
	private javax.swing.JTextField jBookTypeName;
	private javax.swing.JTable jBookTypeTable;
	private javax.swing.JTextField jBookTypeTxt;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	// End of variables declaration//GEN-END:variables

}