/*
 * LogOnFrm.java
 *
 * Created on __DATE__, __TIME__
 */

package hzu.com.cn.view;

import java.sql.Connection;
import java.sql.SQLException;

import hzu.com.cn.dao.UserDao;
import hzu.com.cn.model.User;
import hzu.com.cn.util.DBUtil;

import javax.swing.JOptionPane;

/**
 *
 * @author  __USER__
 */
public class LogOnFrm extends javax.swing.JFrame {
	UserDao userDao = new UserDao();
	DBUtil dbUtil = new DBUtil();

	/** Creates new form LogOnFrm */
	public LogOnFrm() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jUserName = new javax.swing.JTextField();
		jPassword = new javax.swing.JPasswordField();
		jBLogin = new javax.swing.JButton();
		jBReset = new javax.swing.JButton();
		jButton1 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("\u7528\u6237\u767b\u5f55");

		jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18));
		jLabel1.setIcon(new javax.swing.ImageIcon(
				"D:\\Myeclipse\\Workspace\\pic\\logo.png")); // NOI18N
		jLabel1.setText("\u4e66\u5e97\u7ba1\u7406\u7cfb\u7edf");

		jLabel2.setIcon(new javax.swing.ImageIcon(
				"D:\\Myeclipse\\Workspace\\pic\\userName.png")); // NOI18N
		jLabel2.setText("\u7528\u6237\u540d");

		jLabel3.setIcon(new javax.swing.ImageIcon(
				"D:\\Myeclipse\\Workspace\\pic\\password.png")); // NOI18N
		jLabel3.setText("\u5bc6\u7801");

		jBLogin.setIcon(new javax.swing.ImageIcon(
				"D:\\Myeclipse\\Workspace\\pic\\login.png")); // NOI18N
		jBLogin.setText("\u767b\u5f55");
		jBLogin.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jBLoginMouseClicked(evt);
			}
		});
		jBLogin.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				actionPerformed(evt);
			}
		});

		jBReset.setIcon(new javax.swing.ImageIcon(
				"D:\\Myeclipse\\Workspace\\pic\\reset.png")); // NOI18N
		jBReset.setText("\u91cd\u7f6e");
		jBReset.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jBResetMouseClicked(evt);
			}
		});

		jButton1.setText("\u6ce8\u518c");
		jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jButton1MouseClicked(evt);
			}
		});
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				actionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout.createSequentialGroup().addGap(86, 86,
										86).addComponent(jBLogin).addGap(41,
										41, 41).addComponent(jButton1).addGap(
										37, 37, 37).addComponent(jBReset)
										.addContainerGap(48, Short.MAX_VALUE))
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								layout
										.createSequentialGroup()
										.addGap(74, 74, 74)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel2)
														.addComponent(jLabel3))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												29, Short.MAX_VALUE)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(jPassword)
														.addComponent(
																jUserName,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																188,
																Short.MAX_VALUE))
										.addGap(76, 76, 76)).addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								layout.createSequentialGroup().addContainerGap(
										107, Short.MAX_VALUE).addComponent(
										jLabel1).addGap(140, 140, 140)));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGap(24, 24, 24)
										.addComponent(jLabel1)
										.addGap(38, 38, 38)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel2)
														.addComponent(
																jUserName,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jPassword,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel3))
										.addGap(37, 37, 37)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jButton1)
														.addComponent(jBLogin)
														.addComponent(jBReset))
										.addContainerGap(35, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {
		RegisterFrm registerFrm = new RegisterFrm();
		registerFrm.setVisible(true);
	}


	//	private void jBLoginActionPerformed(java.awt.event.ActionEvent evt) {
	//		
	//	}

	private void jBLoginMouseClicked(java.awt.event.MouseEvent evt) {
		String userName = this.jUserName.getText();
		String password = this.jPassword.getText();
		if ("".equals(userName) || userName == null) {
			JOptionPane.showMessageDialog(null, "用户名不能为空");
			return;
		}

		if ("".equals(password) || password == null) {
			JOptionPane.showMessageDialog(null, "密码不能为空");
			return;
		}

		User user = new User(userName, password);
		Connection con = null;
		try {
			con = dbUtil.getCon();
			User currentUser = userDao.login(con, user);
			if (currentUser != null) {
				//JOptionPane.showMessageDialog(null, "恭喜你，登陆成功！");
				this.dispose();
				new MainFrm().setVisible(true);
			} else {
				JOptionPane.showMessageDialog(null, "对不起，您的用戶名或者密碼錯誤！");
			}
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} finally {
			try {
				dbUtil.colseCon(con);
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}

	}

	private void jBResetMouseClicked(java.awt.event.MouseEvent evt) {
		this.jUserName.setText("");
		this.jPassword.setText("");
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new LogOnFrm().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jBLogin;
	private javax.swing.JButton jBReset;
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JPasswordField jPassword;
	private javax.swing.JTextField jUserName;
	// End of variables declaration//GEN-END:variables

}