/*
 * Query_Modify.java
 *
 * Created on __DATE__, __TIME__
 */

package hzu.com.cn.view;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;

import hzu.com.cn.dao.SaleDao;
import hzu.com.cn.dao.StockDao;
import hzu.com.cn.model.Buy;
import hzu.com.cn.model.Sale;
import hzu.com.cn.model.Stock;
import hzu.com.cn.util.DBUtil;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Date;
import java.text.SimpleDateFormat;
/**
 *
 * @author  __USER__
 */
public class Query_Modify extends javax.swing.JFrame {
	DBUtil dbUtil = new DBUtil();
	StockDao stockDao = new StockDao();
	SaleDao saleDao=new SaleDao();

	/** Creates new form Query_Modify */
	public Query_Modify() {
		initComponents();
		jTextAmount.setVisible(false);
		this.fillTable(new Stock());
	}

	private void fillTable(Stock stock) {
		DefaultTableModel dtm = (DefaultTableModel) jBookTable.getModel();
		dtm.setRowCount(0);
		Connection con = null;
		try {
			con = dbUtil.getCon();
			ResultSet rs = stockDao.bookTyeList(con, stock);
			while (rs.next()) {
				Vector v = new Vector();
				v.add(rs.getString("id"));
				v.add(rs.getString("bookName"));
				v.add(rs.getString("author"));
				v.add(rs.getString("price"));
				v.add(rs.getString("press"));
				v.add(rs.getString("amount"));
				dtm.addRow(v);
			}
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} finally {

			try {
				dbUtil.getCon();
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}

		}
	}
	
	public String time(){
		SimpleDateFormat df=new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
		return df.format(new Date());
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jTBookName = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		jBookTable = new javax.swing.JTable();
		jPanel1 = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jTBookId = new javax.swing.JTextField();
		jTbookname = new javax.swing.JTextField();
		jTBookAthor = new javax.swing.JTextField();
		jTBookPress = new javax.swing.JTextField();
		jTBookPrice = new javax.swing.JTextField();
		jButton2 = new javax.swing.JButton();
		jPanel2 = new javax.swing.JPanel();
		jLabel7 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		jButton4 = new javax.swing.JButton();
		jTextAmount = new javax.swing.JTextField();
		jTAmount = new javax.swing.JTextField();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("\u56fe\u4e66\u67e5\u8be2\u53ca\u4fee\u6539");

		jLabel1.setText("\u4e66\u540d");

		jButton1.setText("\u67e5\u8be2");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jBookTable.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] {

				}, new String[] { "编号", "书名", "作者", "价格", "出版社", "数量" }) {
			boolean[] canEdit = new boolean[] { false, false, false, false,
					false, false };

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		});
		jBookTable.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				jBookTableMousePressed(evt);
			}
		});
		jScrollPane1.setViewportView(jBookTable);

		jPanel1.setBorder(javax.swing.BorderFactory
				.createTitledBorder("\u56fe\u4e66\u4fe1\u606f\u4fee\u6539"));

		jLabel2.setText("\u56fe\u4e66\u7f16\u53f7");

		jLabel3.setText("\u4e66\u540d");

		jLabel4.setText("\u4f5c\u8005");

		jLabel5.setText("\u56fe\u4e66\u4ef7\u683c");

		jLabel6.setText("\u51fa\u7248\u793e");

		jButton2.setText("\u4fee\u6539");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGap(32, 32, 32)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel5)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jTBookPrice,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				108,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING)
																						.addComponent(
																								jLabel4)
																						.addComponent(
																								jLabel2))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								false)
																						.addComponent(
																								jTBookAthor)
																						.addComponent(
																								jTBookId,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								79,
																								Short.MAX_VALUE))
																		.addGap(
																				24,
																				24,
																				24)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING)
																						.addComponent(
																								jLabel3)
																						.addComponent(
																								jLabel6))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								false)
																						.addComponent(
																								jTBookPress)
																						.addComponent(
																								jTbookname,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								105,
																								Short.MAX_VALUE)))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGap(
																				126,
																				126,
																				126)
																		.addComponent(
																				jButton2)))
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel2)
														.addComponent(
																jTBookId,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel3)
														.addComponent(
																jTbookname,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel6)
														.addComponent(
																jTBookPress,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel4)
														.addComponent(
																jTBookAthor,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(28, 28, 28)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel5)
														.addComponent(
																jTBookPrice,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(45, 45, 45).addComponent(
												jButton2).addContainerGap(53,
												Short.MAX_VALUE)));

		jPanel2.setBorder(javax.swing.BorderFactory
				.createTitledBorder(javax.swing.BorderFactory
						.createTitledBorder(javax.swing.BorderFactory
								.createTitledBorder("\u9500\u552e"))));

		jLabel7.setText("\u8d2d\u4e70\u6570\u91cf");

		jButton4.setText("\u786e\u8ba4");
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton4ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout
				.setHorizontalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel2Layout
										.createSequentialGroup()
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel2Layout
																		.createSequentialGroup()
																		.addGap(
																				203,
																				203,
																				203)
																		.addComponent(
																				jLabel8,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				53,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																jPanel2Layout
																		.createSequentialGroup()
																		.addGap(
																				75,
																				75,
																				75)
																		.addComponent(
																				jButton4,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				90,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																jPanel2Layout
																		.createSequentialGroup()
																		.addGap(
																				32,
																				32,
																				32)
																		.addComponent(
																				jLabel7)
																		.addGap(
																				18,
																				18,
																				18)
																		.addComponent(
																				jTAmount,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				92,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addContainerGap(28, Short.MAX_VALUE))
						.addGroup(
								jPanel2Layout.createSequentialGroup().addGap(
										68, 68, 68).addComponent(jTextAmount,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										108, Short.MAX_VALUE).addGap(108, 108,
										108)));
		jPanel2Layout
				.setVerticalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel2Layout
										.createSequentialGroup()
										.addComponent(
												jTextAmount,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												23,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(50, 50, 50)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel7)
														.addComponent(
																jTAmount,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(55, 55, 55).addComponent(
												jButton4).addGap(11, 11, 11)
										.addComponent(jLabel8).addContainerGap(
												49, Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGap(53, 53, 53)
										.addComponent(
												jPanel2,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(63, 63, 63)
										.addComponent(
												jPanel1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(53, Short.MAX_VALUE))
						.addGroup(
								layout.createSequentialGroup().addGap(174, 174,
										174).addComponent(jScrollPane1).addGap(
										213, 213, 213))
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								layout
										.createSequentialGroup()
										.addGap(211, 211, 211)
										.addComponent(jLabel1)
										.addGap(29, 29, 29)
										.addComponent(
												jTBookName,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												216,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												64, Short.MAX_VALUE)
										.addComponent(jButton1).addGap(238,
												238, 238)));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGap(63, 63, 63)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jButton1)
														.addComponent(jLabel1)
														.addComponent(
																jTBookName,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addComponent(
												jScrollPane1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												215,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(
																jPanel1,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																jPanel2,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE))
										.addGap(25, 25, 25)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
		String amount = this.jTextAmount.getText();
		String amount_1=this.jTAmount.getText();
		String id=this.jTBookId.getText();
		
		if ("".equals(amount_1) || amount_1 == null) {
			JOptionPane.showMessageDialog(null, "请输入要购买的数量！");
			return;
		}
		boolean y=(Integer.parseInt(amount)-Integer.parseInt(amount_1))>0||(Integer.parseInt(amount)-Integer.parseInt(amount_1)==0);
		if(y){
			Stock stock = new Stock(Integer.parseInt(id),Integer.parseInt(amount)-Integer.parseInt(amount_1));
			Connection con = null;

			try {
				con = dbUtil.getCon();
				int modifyNum = stockDao.stockEditAm(con, stock);
				if (modifyNum == 1) {

					JOptionPane.showMessageDialog(null, "操作成功！");
//////////////////////////////////////////					
					String time=this.time();
					Sale sale=new Sale(this.jTbookname.getText(),  this.jTBookAthor.getText(),  Float.parseFloat(this.jTBookPrice.getText()),  this.jTBookPress.getText(),Integer.parseInt(this.jTextAmount.getText()), time);
					con = null;
					try {
						con = dbUtil.getCon();
						int add = saleDao.saleAdd(con, sale);

						if (add == 1) {
							JOptionPane.showMessageDialog(null, "购买记录已经更新！");
							this.resetValue();
						} else {
							JOptionPane.showMessageDialog(null, "购买记录更新失败！");
						}
					} catch (Exception e) {
						// TODO Auto-generated catch block
						e.printStackTrace();
						JOptionPane.showMessageDialog(null, "购买记录更新失败！");
					} finally {
						try {
							dbUtil.colseCon(con);
						} catch (SQLException e) {
							// TODO Auto-generated catch block
							e.printStackTrace();
						}
					}	
					
////////////////////////////////////////////////////					
					this.jTAmount.setText("");
					this.fillTable(new Stock());

				} else {

					JOptionPane.showMessageDialog(null, "操作失败！");
				}

			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
				JOptionPane.showMessageDialog(null, "操作失败！");
			}
		}else{
			JOptionPane.showMessageDialog(null, "库存不足！");
			this.jTAmount.setText("");
		}
	}

	private void jBookTableMousePressed(java.awt.event.MouseEvent evt) {
		int row = jBookTable.getSelectedRow();
		this.jTBookId.setText((String) jBookTable.getValueAt(row, 0));
		this.jTbookname.setText((String) jBookTable.getValueAt(row, 1));
		this.jTBookAthor.setText((String) jBookTable.getValueAt(row, 2));
		this.jTBookPrice.setText((String) jBookTable.getValueAt(row, 3));
		this.jTBookPress.setText((String) jBookTable.getValueAt(row, 4));
		this.jTextAmount.setText((String) jBookTable.getValueAt(row, 5));
	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		String id = this.jTBookId.getText();
		//		int id = Integer.parseInt(this.jTBookId.getText());
		String bookName = this.jTbookname.getText();
		String bookAthor = this.jTBookAthor.getText();
		//		String bookPrice=this.jTBookPrice.getText();
		float bookPrice = Float.parseFloat(this.jTBookPrice.getText());
		String bookPress = this.jTBookPress.getText();
		if ("".equals(id) || id == null) {
			JOptionPane.showMessageDialog(null, "请选择要修改的记录");
			return;
		}
		//		Stock stock=new Stock(Integer.parseInt(id), bookName, bookAthor, bookPrice),bookPress);	
		Stock stock = new Stock(Integer.parseInt(id), bookName, bookAthor,
				bookPrice, bookPress);
		Connection con = null;

		try {
			con = dbUtil.getCon();
			int modifyNum = stockDao.stockModify(con, stock);
			if (modifyNum == 1) {

				JOptionPane.showMessageDialog(null, "修改成功！");
				this.resetValue();
				this.fillTable(new Stock());

			} else {

				JOptionPane.showMessageDialog(null, "修改失败！");
			}

		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
			JOptionPane.showMessageDialog(null, "修改失败！");
		}
	}

	private void resetValue() {
		this.jTBookId.setText("");
		this.jTBookName.setText("");
		this.jTBookAthor.setText("");
		this.jTBookPress.setText("");
		this.jTBookPrice.setText("");
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		String bookname = this.jTBookName.getText();
		Stock stock = new Stock();
		stock.setBookName(bookname);
		this.fillTable(stock);
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Query_Modify().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JTable jBookTable;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton4;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextField jTAmount;
	private javax.swing.JTextField jTBookAthor;
	private javax.swing.JTextField jTBookId;
	private javax.swing.JTextField jTBookName;
	private javax.swing.JTextField jTBookPress;
	private javax.swing.JTextField jTBookPrice;
	private javax.swing.JTextField jTbookname;
	private javax.swing.JTextField jTextAmount;
	// End of variables declaration//GEN-END:variables

}