/*
 * UserEditFrm.java
 *
 * Created on __DATE__, __TIME__
 */

package hzu.com.cn.view;

import hzu.com.cn.dao.UserDao;
import hzu.com.cn.model.BookType;
import hzu.com.cn.model.Stock;
import hzu.com.cn.model.User;
import hzu.com.cn.util.DBUtil;

import java.sql.Connection;
import java.sql.ResultSet;
import java.util.Vector;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author  __USER__
 */
public class UserEditFrm extends javax.swing.JInternalFrame {
	DBUtil dbUtil = new DBUtil();
	UserDao userDao = new UserDao();

	/** Creates new form UserEditFrm */
	public UserEditFrm() {
		initComponents();
		this.jUserId.setVisible(false);
		this.fillTable(new User());
	}

	private void fillTable(User user) {
		DefaultTableModel dtm = (DefaultTableModel) jTableUser.getModel();
		dtm.setRowCount(0);
		Connection con = null;
		try {
			con = dbUtil.getCon();
			ResultSet rs = userDao.userList(con, user);
			while (rs.next()) {
				Vector v = new Vector();
				v.add(rs.getString("id"));
				v.add(rs.getString("username"));
				v.add(rs.getString("password"));
				dtm.addRow(v);
			}
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} finally {

			try {
				dbUtil.getCon();
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}

		}
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jTAccount = new javax.swing.JTextField();
		jTPassword = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTableUser = new javax.swing.JTable();
		jUserId = new javax.swing.JLabel();

		setBorder(javax.swing.BorderFactory
				.createTitledBorder(javax.swing.BorderFactory
						.createTitledBorder("\u7528\u6237\u4e2a\u4eba\u4fe1\u606f\u7ba1\u7406")));
		setClosable(true);
		setIconifiable(true);

		jLabel1.setText("\u66f4\u6539\u8d26\u53f7");

		jLabel2.setText("\u66f4\u6539\u5bc6\u7801");

		jButton1.setText("\u66f4\u6539");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jTableUser.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] {

				}, new String[] { "编号", "账户名", "密码" }) {
			boolean[] canEdit = new boolean[] { true, false, false };

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		});
		jTableUser.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				jTableUserMousePressed(evt);
			}
		});
		jScrollPane1.setViewportView(jTableUser);

		jUserId.setText("jLabel3");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING,
																				false)
																		.addGroup(
																				javax.swing.GroupLayout.Alignment.LEADING,
																				layout
																						.createSequentialGroup()
																						.addGap(
																								65,
																								65,
																								65)
																						.addComponent(
																								jLabel1)
																						.addGap(
																								18,
																								18,
																								18)
																						.addComponent(
																								jTAccount,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								75,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addPreferredGap(
																								javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								Short.MAX_VALUE)
																						.addComponent(
																								jLabel2)
																						.addGap(
																								28,
																								28,
																								28)
																						.addComponent(
																								jTPassword,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								85,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addGap(
																								34,
																								34,
																								34))
																		.addGroup(
																				javax.swing.GroupLayout.Alignment.LEADING,
																				layout
																						.createSequentialGroup()
																						.addGap(
																								55,
																								55,
																								55)
																						.addComponent(
																								jScrollPane1,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								437,
																								javax.swing.GroupLayout.PREFERRED_SIZE)))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGap(
																				223,
																				223,
																				223)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING)
																						.addComponent(
																								jUserId)
																						.addComponent(
																								jButton1))))
										.addContainerGap(41, Short.MAX_VALUE)));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGap(37, 37, 37)
										.addComponent(
												jScrollPane1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												67,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(jUserId)
										.addGap(22, 22, 22)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel1)
														.addComponent(
																jTAccount,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jLabel2,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																17,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jTPassword,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(42, 42, 42).addComponent(
												jButton1).addContainerGap(59,
												Short.MAX_VALUE)));

		getAccessibleContext().setAccessibleName("null");

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jTableUserMousePressed(java.awt.event.MouseEvent evt) {
		int row = jTableUser.getSelectedRow();
		this.jUserId.setText((String) jTableUser.getValueAt(row, 0));
		this.jTAccount.setText((String) jTableUser.getValueAt(row, 1));
		this.jTPassword.setText((String) jTableUser.getValueAt(row, 2));
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		String id=this.jUserId.getText();
		String account = this.jTAccount.getText();
		String password = this.jTPassword.getText();
		if ("".equals(account) || account == null) {
			JOptionPane.showMessageDialog(null, "账户名不能为空！");
			return;
		}
		if ("".equals(password) || password == null) {
			JOptionPane.showMessageDialog(null, "密码不能为空！");
			return;
		}
		User user = new User(Integer.parseInt(id),account, password);
		int n = JOptionPane.showConfirmDialog(null, "确定要更改吗？");
		if (n == 0) {
			Connection con = null;
			try {
				con = dbUtil.getCon();
				int editNumber = userDao.userModify(con, user);
				System.out.println(editNumber);
				if (editNumber == 1) {
					JOptionPane.showMessageDialog(null, "更改成功！");
					this.jTAccount.setText("");
					this.jTPassword.setText("");
					this.fillTable(new User());
				} else {
					JOptionPane.showMessageDialog(null, "更改失败！");
				}

			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
				JOptionPane.showMessageDialog(null, "更改失败！");
			}

		}
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextField jTAccount;
	private javax.swing.JTextField jTPassword;
	private javax.swing.JTable jTableUser;
	private javax.swing.JLabel jUserId;
	// End of variables declaration//GEN-END:variables

}